# this will deploy the safe / secure / tested app to Prod server
name: Deploy To Local

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
      DOCKER_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            --username "${{ vars.DOCKERHUB_USER }}" \
            --password-stdin

      - name: Deploy application
        run: |
          export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
          export DOCKER_TAG=${{ github.sha }}

          docker compose down
          docker compose pull
          docker compose up -d --force-recreate
